[package]
name = "supersuitoken"
version = "1.0.0"
edition = "2024"
published-at = "0x3ef50064e39071fc326da67cfbea4a5905a80541d8a95dc07ff28e320c772389"

[addresses]
ssui = "0x3ef50064e39071fc326da67cfbea4a5905a80541d8a95dc07ff28e320c772389"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.62.0" }
